version: '3.3'
services:
        #   cerebro:
        #     image: lmenezes/cerebro
        #     ports:
        #       - 9000:9000
        #     networks:
        #       - elastic
        #     deploy:
        #       placement:
        #         constraints:
        #           - node.labels.id==1
  nginx:
    image: nginx:alpine
    configs:
      - source: nginx_htpasswd
        target: /etc/nginx/nginx.htpasswd
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    networks:
      - elastic
    ports:
      - 80:80
    deploy:
      mode: replicated
      replicas: 1
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - 5601:5601
    networks:
      - elastic
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 800M
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - network.host=0
      - network.publish_host=_eth0_
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
    privileged: yes
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 990M
      placement:
        constraints:
          - node.labels.id==2
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - network.host=_eth0_
      - network.publish_host=_eth0_
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
    privileged: yes
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 990M
      placement:
        constraints:
          - node.labels.id==1
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - network.host=_eth0_
      - network.publish_host=_eth0_
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - elastic
    privileged: yes
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 990M
      placement:
        constraints:
          - node.labels.id==2

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: overlay
configs:
  nginx_config:
    file: ./nginx.conf
  nginx_htpasswd:
    file: ./nginx.htpasswd
